### ISSUE TITLE
premodels on coco

### ISSUE THREAD

**Issue by whut2962575697** [PanJianning/cbnet#1]
Hello, thanks for your great work! Can you share the models trained on coco?

**Comment by panjianning** [comment]
> Hello, thanks for your great work! Can you share the models trained on coco?

Which one, resnetvd200 or res2net101?

**Comment by whut2962575697** [comment]
can you privide both of two?

**Comment by whut2962575697** [comment]
thank you very much! you can sent to my email: 2962575697@whut.edu.cn

**Comment by panjianning** [comment]
> can you privide both of two?

Please check your email.

**Comment by luuuyi** [comment]
Nice work! Can you share your CBNet with resnet200_vd and resnet200_vd weights to me? My email is 435977170@qq.com
