### ISSUE TITLE
COCO pretrain model

### ISSUE THREAD

**Issue by zhengye1995** [PanJianning/cbnet#2]
Thanks for your awesome work, can you share me the COCO pretrain model for CBNET~

**Comment by panjianning** [comment]
> Thanks for your awesome work, can you share me the COCO pretrain model for CBNET~

Nope, since we are in the same competition now~

**Comment by zhengye1995** [comment]
Got it,  I had to train itb by myself.

**Comment by panjianning** [comment]
> Got it, I had to train itb by myself.

You could try to transfer the weights in PaddleDetection to mmdetection.

**Comment by zhengye1995** [comment]
Thx, I will try it.
