### ISSUE TITLE
coco pretrain model

### ISSUE THREAD

**Issue by lz75258** [PanJianning/cbnet#4]
Hello, thanks for your great work! Can you share the models trained on coco  for cbnet?  My email is 739337660@qq.com

**Comment by lddsjy** [comment]
I want the cbnet weights on coco as well. Would you mind sharing it? Thanks a lot! 710910630@qq.com

**Comment by panjianning** [comment]
Already send. Please clone mmdet 1.1.0, place the files（cbnet.py, resnet_vd.py, non_local.py, etc.） in the right directory and write config following the readme.
