### ISSUE TITLE
COCO model

### ISSUE THREAD

**Issue by lddsjy** [PanJianning/cbnet#5]
Thanks for your work! Found your repo in [https://github.com/VDIGPKU/CBNet.git](url)
Could you please share your cbnet model which can be directly tested on coco? In VDIGPKU's repository, using convert_db.py to convert model_zoo models to cbnet version cannot get weights of composite connections, right? If I want to test cbnet version models on coco, after python convert_db.py, I have to train a model by tools/train.py .  That's tricky since my gpu cannot allocate a lot of memory.

**Comment by panjianning** [comment]
> Using convert_db.py to convert model_zoo models to cbnet version cannot get weights of composite connections, right?

It only gives you the imagenet-pretrained weights of backbone.

**Comment by lddsjy** [comment]
> Using convert_db.py to convert model_zoo models to cbnet version cannot get weights of composite connections, right?
> 
> It only gives you the imagenet-pretrained weights of backbone.

Thanks a lot! Have you tried to convert pth model into onnx? When running pytorch2onnx.py in mmdetection, an error like 'Couldn't export Python operator _RoIAlignFunction' happens.

**Comment by panjianning** [comment]
> Thanks a lot! Have you tried to convert pth model into onnx? When running pytorch2onnx.py in mmdetection, an error like 'Couldn't export Python operator _RoIAlignFunction' happens.

I have no experience in converting pytorch model into onnx.
