### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by SnailForce** [PanJianning/cbnet#6]
Can you write about where the four files should be placed？Thanks.

**Comment by panjianning** [comment]
* non_local.py should be placed in https://github.com/open-mmlab/mmdetection/tree/v1.1.0/mmdet/models/plugins

* the other three backbone files should be placed in https://github.com/open-mmlab/mmdetection/tree/v1.1.0/mmdet/models/detectors

MMdetection2.x is very different from MMdetection1.x, be careful to use it when trying to use it in 2.x.
